pub type boolean = u32;
pub type pixel_t = u32;
pub const NULL: *mut ::core::ffi::c_void = ::core::ptr::null_mut::<::core::ffi::c_void>();
pub const true_0: i32 = 1;
pub const false_0: i32 = 0;
pub const MAXPLAYERS: i32 = 4;
pub const TICRATE: i32 = 35;
pub const SCREENWIDTH: i32 = 320;
pub const SCREENHEIGHT: i32 = 200;
